
DROP TABLE IF EXISTS Feedback;
DROP TABLE IF EXISTS Participates;
DROP TABLE IF EXISTS supplies;
DROP TABLE IF EXISTS Activity;
DROP TABLE IF EXISTS Resident;
DROP TABLE IF EXISTS Instructor;
DROP TABLE IF EXISTS Supplier;
